import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Link from 'next/link';
import SiteShell from '@/components/corporate/SiteShell';
import { PageHero, CTA, Section } from '@/components/corporate/PageParts';
import { services, industries, caseStudies } from '@/content/corporate';
export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);return s?{title:s.name,description:s.short,alternates:{canonical:`/services/${s.slug}`}}:{};}
export default async function Service({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)return notFound();return <SiteShell><PageHero eyebrow="Service" title={s.name} body={s.short} crumbs={[{label:'Services',href:'/services'},{label:s.name}]}/><Section><div className="q-detail-grid"><div><p className="q-eyebrow">Business challenges</p><h2>Move past the constraints.</h2></div><div><ul>{s.challenges.map(x=><li key={x}>{x}</li>)}</ul><h2>Solution overview</h2><p className="q-body">We shape a practical path from the current operating reality to a more capable, dependable service—combining focused discovery with hands-on delivery.</p><h2>Capabilities</h2><div className="q-tags">{s.capabilities.map(x=><span className="q-tag" key={x}>{x}</span>)}</div><h2>Delivery approach</h2><p className="q-body">Discover, design, engineer, and evolve the service in useful increments with the people who run it.</p><h2>Technologies used</h2><div className="q-tags">{s.technologies.map(x=><span className="q-tag" key={x}>{x}</span>)}</div></div></div></Section><Section className="alt"><div className="q-detail-grid"><div><p className="q-eyebrow">Benefits</p><h2>Progress you can sustain.</h2></div><div><ul><li>Clearer priorities and a delivery path tied to important work.</li><li>Technology choices appropriate to the operating context.</li><li>Visible, collaborative delivery that supports adoption.</li></ul><h2>Industries served</h2><div className="q-tags">{industries.slice(0,6).map(x=><Link className="q-tag" href={`/industries/${x.slug}`} key={x.slug}>{x.name}</Link>)}</div><h2>Related case studies</h2><p className="q-body">Approved project details are pending. <Link className="q-link" href={`/resources/case-studies/${caseStudies[0].slug}`}>View the replacement-ready framework</Link>.</p></div></div></Section><Section><div className="q-detail-grid"><div><p className="q-eyebrow">Frequently asked questions</p><h2>Starting with the right questions.</h2></div><div><details><summary>How do we begin?</summary><p>We begin with the context, constraints, and outcomes that matter to your team.</p></details><details><summary>Can this work alongside our internal team?</summary><p>Yes. Our delivery approach is designed to make decisions and ownership clear across teams.</p></details></div></div></Section><CTA/></SiteShell>;}
