import {describe,it,expect} from 'vitest';import {MysqlBacktestOwnershipAuthority} from '@/lib/backtesting/queue/ownershipAuthority';
class FakeDb{state:any={owner:'monolith',epoch:4,updated_at:'2026-08-03T00:00:00Z',updated_by:'seed'};active:any[]=[];missing=false;async query(sql:string,p:any[]=[]):Promise<any>{if(sql.includes("status IN ('running'"))return{rows:this.active};if(sql.startsWith('SELECT'))return{rows:this.missing?[]:[this.state]};if(sql.startsWith('UPDATE')){if(p[2]!==this.state.epoch||p[3]!==this.state.owner)return{rows:[],affectedRows:0};this.state={owner:p[0],epoch:this.state.epoch+1,updated_at:'2026-08-03T00:00:01Z',updated_by:p[1]};return{rows:[],affectedRows:1}}return{rows:[]}}}
describe('MySQL ownership authority',()=>{
 it('reads and validates state',async()=>{const db=new FakeDb();expect(await new MysqlBacktestOwnershipAuthority(db as any).read()).toMatchObject({owner:'monolith',epoch:4,updatedBy:'seed'});db.missing=true;await expect(new MysqlBacktestOwnershipAuthority(db as any).read()).rejects.toMatchObject({code:'missing'})});
 it.each([['bogus',4,'invalid-owner'],['monolith',0,'invalid-epoch'],['monolith',-1,'invalid-epoch']])('rejects invalid %s/%s',async(owner,epoch,code)=>{const db=new FakeDb();db.state={...db.state,owner,epoch};await expect(new MysqlBacktestOwnershipAuthority(db as any).read()).rejects.toMatchObject({code})});
 it('requires operator, expected epoch, safe graph, and increments once',async()=>{const db=new FakeDb();const a=new MysqlBacktestOwnershipAuthority(db as any);await expect(a.transition(4,'disabled','',false)).rejects.toMatchObject({code:'operator-required'});await expect(a.transition(3,'disabled','op',false)).rejects.toMatchObject({code:'stale-epoch'});await expect(a.transition(4,'service','op',false)).rejects.toMatchObject({code:'unsafe-transition'});expect((await a.transition(4,'disabled','op',false)).epoch).toBe(5);expect(db.state.epoch).toBe(5)});
 it('supports the complete safe graph and blocks leaving disabled with active jobs',async()=>{for(const [from,to] of [['monolith','disabled'],['service','disabled'],['disabled','service'],['disabled','monolith']] as const){const db=new FakeDb();db.state={...db.state,owner:from};expect((await new MysqlBacktestOwnershipAuthority(db as any).transition(4,to,'op',false)).owner).toBe(to)}const db=new FakeDb();db.state={...db.state,owner:'disabled'};db.active=[{count:1}];await expect(new MysqlBacktestOwnershipAuthority(db as any).transition(4,'service','op',false)).rejects.toMatchObject({code:'unsafe-active-jobs'})});
 it('allows only one concurrent compare-and-set winner',async()=>{const db=new FakeDb();const a=new MysqlBacktestOwnershipAuthority(db as any);const results=await Promise.allSettled([a.transition(4,'disabled','a',false),a.transition(4,'disabled','b',false)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1)});
});
