export type VerificationStatus = 'verified' | 'anonymized' | 'placeholder';

export const brand = {
  name: 'Quantorus',
  url: 'https://quantorus.example',
  headline: 'Technology engineered for meaningful business progress.',
  description: 'Quantorus combines strategy, software engineering, cloud, data, automation, cybersecurity, and AI to help organisations modernise operations, improve digital experiences, and build scalable technology foundations.',
  contactEmail: 'saurabh@quantorus.in',
};

export const services = [
  { slug: 'artificial-intelligence', name: 'Artificial Intelligence', short: 'Put practical intelligence to work in the decisions and workflows that matter.', challenges: ['Unclear AI opportunities', 'Manual knowledge work', 'Governance and adoption concerns'], capabilities: ['AI opportunity mapping', 'Applied AI solutions', 'Responsible delivery'], technologies: ['Python', 'LLM APIs', 'Data platforms', 'Cloud APIs'] },
  { slug: 'data-analytics', name: 'Data & Analytics', short: 'Create data foundations that give teams a clearer view of the work.', challenges: ['Fragmented information', 'Slow reporting', 'Inconsistent metrics'], capabilities: ['Data strategy', 'Analytics products', 'Decision intelligence'], technologies: ['SQL', 'Python', 'BI tools', 'Cloud data services'] },
  { slug: 'cloud-services', name: 'Cloud Services', short: 'Build resilient cloud foundations for secure, sustainable delivery.', challenges: ['Legacy hosting', 'Scaling constraints', 'Release friction'], capabilities: ['Cloud architecture', 'Modernisation', 'Platform operations'], technologies: ['AWS', 'Docker', 'CI/CD', 'Observability'] },
  { slug: 'cybersecurity', name: 'Cybersecurity', short: 'Design security-minded technology practices into every stage of delivery.', challenges: ['Security gaps', 'Risk visibility', 'Complex compliance needs'], capabilities: ['Security reviews', 'Secure engineering', 'Risk-aware delivery'], technologies: ['Identity controls', 'Security testing', 'Monitoring'] },
  { slug: 'ai-data-automation', name: 'AI, Data & Intelligent Automation', short: 'Make complex information useful, repeatable, and ready for action.', challenges: ['Information spread across systems', 'Manual, error-prone workflows', 'Unclear path from data to decisions'], capabilities: ['Data foundations', 'Applied AI workflows', 'Operational automation'], technologies: ['Python', 'TypeScript', 'SQL', 'Cloud APIs'] },
  { slug: 'digital-product-engineering', name: 'Digital Product Engineering', short: 'Build dependable digital products that people can use and teams can evolve.', challenges: ['Slow product delivery', 'Legacy user experiences', 'Disconnected customer journeys'], capabilities: ['Product delivery', 'Web applications', 'Platform integration'], technologies: ['Next.js', 'React', 'Node.js', 'PostgreSQL'] },
  { slug: 'enterprise-applications', name: 'Enterprise Applications', short: 'Connect critical systems into dependable, usable operational platforms.', challenges: ['Disconnected systems', 'Inefficient operations', 'Limited platform flexibility'], capabilities: ['Platform integration', 'Application delivery', 'Workflow design'], technologies: ['APIs', 'TypeScript', 'Databases', 'Cloud services'] },
  { slug: 'business-process-automation', name: 'Business Process Automation', short: 'Turn repetitive operational work into reliable, visible systems.', challenges: ['Manual handoffs', 'Inconsistent processes', 'Limited operational visibility'], capabilities: ['Workflow mapping', 'Systems integration', 'Process intelligence'], technologies: ['APIs', 'Automation platforms', 'Analytics'] },
  { slug: 'managed-services', name: 'Managed Services', short: 'Maintain and evolve essential digital systems with visibility and care.', challenges: ['Unplanned operational work', 'Limited in-house capacity', 'Inconsistent monitoring'], capabilities: ['Operational support', 'Optimisation', 'Service improvement'], technologies: ['Monitoring', 'Automation', 'Cloud platforms'] },
  { slug: 'technology-strategy', name: 'Technology Strategy & Consulting', short: 'Align technology decisions with business priorities and execution.', challenges: ['Unclear investment priorities', 'Fragmented roadmaps', 'Delivery risk'], capabilities: ['Technology roadmaps', 'Operating models', 'Delivery planning'], technologies: ['Discovery workshops', 'Architecture reviews', 'Roadmapping'] },
] as const;

export const industries = [
  { slug: 'financial-services', name: 'Financial Services', headline: 'Technology foundations for trusted, responsive financial services.', challenges: ['Complex customer journeys', 'Operational resilience', 'Evolving risk expectations'] },
  { slug: 'healthcare', name: 'Healthcare', headline: 'Thoughtful digital systems for high-stakes experiences.', challenges: ['Fragmented workflows', 'Information accessibility', 'Reliability requirements'] },
  { slug: 'retail-ecommerce', name: 'Retail & E-commerce', headline: 'Connected experiences for customers and operational teams.', challenges: ['Changing customer expectations', 'Channel fragmentation', 'Operational scale'] },
  { slug: 'manufacturing', name: 'Manufacturing', headline: 'Better visibility across complex operations.', challenges: ['Siloed operational data', 'Manual processes', 'Legacy environments'] },
  { slug: 'technology-saas', name: 'Technology & SaaS', headline: 'Products and platforms built for change.', challenges: ['Rapidly evolving customer expectations', 'Complex platform decisions', 'Pressure to deliver without compromising quality'] },
  { slug: 'professional-services', name: 'Professional Services', headline: 'More connected operations for expert teams.', challenges: ['Knowledge trapped in teams', 'Manual delivery processes', 'Fragmented client experiences'] },
  { slug: 'logistics', name: 'Logistics', headline: 'More visible, connected operations across the movement of goods.', challenges: ['Fragmented operational visibility', 'Manual coordination', 'Changing service expectations'] },
  { slug: 'education', name: 'Education', headline: 'Digital services designed around learning and operations.', challenges: ['Disconnected learner experiences', 'Administrative burden', 'Accessibility requirements'] },
  { slug: 'government', name: 'Government', headline: 'Digital delivery designed for public value and accountability.', challenges: ['Complex service journeys', 'Legacy systems', 'Accessibility and assurance needs'] },
] as const;

export const caseStudies = [
  { slug: 'digital-platform-placeholder', title: 'A clearer path from operational complexity to a digital platform', industry: 'Technology & SaaS', service: 'Digital Product Engineering', challenge: 'A client engagement requires confirmation before public detail can be shared.', solution: 'Placeholder — replace with a verified, client-approved project summary.', result: 'Outcome details pending verification.', verificationStatus: 'placeholder' as VerificationStatus, sourceNotes: 'Upwork profile endpoint was not publicly accessible during site build. Replace with approved source material.' },
  { slug: 'automation-workflow-placeholder', title: 'Designing a more reliable workflow for a growing operation', industry: 'Professional Services', service: 'Business Process Automation', challenge: 'A client engagement requires confirmation before public detail can be shared.', solution: 'Placeholder — replace with a verified, client-approved project summary.', result: 'Outcome details pending verification.', verificationStatus: 'placeholder' as VerificationStatus, sourceNotes: 'Upwork profile endpoint was not publicly accessible during site build. Replace with approved source material.' },
  { slug: 'data-decision-placeholder', title: 'Making business data easier to understand and act on', industry: 'Technology & SaaS', service: 'AI, Data & Intelligent Automation', challenge: 'A client engagement requires confirmation before public detail can be shared.', solution: 'Placeholder — replace with a verified, client-approved project summary.', result: 'Outcome details pending verification.', verificationStatus: 'placeholder' as VerificationStatus, sourceNotes: 'Upwork profile endpoint was not publicly accessible during site build. Replace with approved source material.' },
] as const;

export const jobs = [
  { slug: 'frontend-developer', title: 'Frontend Developer', type: 'Full-time · Placeholder', summary: 'Build accessible, high-performing interfaces for enterprise digital products.', requirements: ['Strong React and TypeScript foundations', 'Experience translating product designs into robust UI', 'Thoughtful approach to accessibility and responsive delivery'] },
  { slug: 'power-bi-specialist', title: 'Power BI Specialist', type: 'Full-time · Placeholder', summary: 'Create clear, trusted reporting and decision-support experiences from operational data.', requirements: ['Power BI data modelling and dashboard delivery', 'SQL and stakeholder communication skills', 'Attention to metric definitions and data quality'] },
  { slug: 'oracle-dba', title: 'Oracle DBA', type: 'Full-time · Placeholder', summary: 'Support dependable, secure, and well-managed Oracle database environments.', requirements: ['Oracle database administration experience', 'Performance tuning, backup, and recovery knowledge', 'Operational discipline and documentation habits'] },
  { slug: 'genai-specialist', title: 'GenAI Specialist', type: 'Full-time · Placeholder', summary: 'Help shape responsible generative-AI solutions around real business workflows.', requirements: ['Applied LLM and AI solution experience', 'Understanding of evaluation, governance, and data handling', 'Ability to connect technical possibilities to operating needs'] },
] as const;

export const navItems = [
  { label: 'What we do', href: '/services' }, { label: 'Industries', href: '/industries' }, { label: 'Technologies', href: '/technologies' }, { label: 'Insights', href: '/insights' }, { label: 'About', href: '/about' }, { label: 'Careers', href: '/careers' }, { label: 'Contact', href: '/contact' },
];

export const technologies = [
  { slug: 'cloud-platforms', name: 'Cloud platforms', category: 'Cloud', description: 'Foundations for resilient, flexible digital services.' },
  { slug: 'ai-machine-learning', name: 'AI & machine learning', category: 'AI & machine learning', description: 'Practical intelligence applied with purpose and governance.' },
  { slug: 'data-platforms', name: 'Data platforms', category: 'Data platforms', description: 'Reliable data services that teams can trust.' },
  { slug: 'enterprise-platforms', name: 'Enterprise platforms', category: 'Enterprise platforms', description: 'Connected applications for operational clarity.' },
  { slug: 'devops-automation', name: 'DevOps & automation', category: 'DevOps', description: 'A faster, safer path from change to delivery.' },
  { slug: 'cybersecurity-platforms', name: 'Cybersecurity platforms', category: 'Security', description: 'Security-aware systems for evolving digital risk.' },
  { slug: 'frontend', name: 'Frontend engineering', category: 'Frontend', description: 'Accessible, performant interfaces built around real user needs.' },
  { slug: 'backend', name: 'Backend engineering', category: 'Backend', description: 'Reliable services and integrations that support sustainable delivery.' },
  { slug: 'mobile', name: 'Mobile development', category: 'Mobile', description: 'Mobile experiences connected to the wider service ecosystem.' },
] as const;

export const insights = [
  { slug: 'ai-adoption-without-the-hype', title: 'AI adoption without the hype', category: 'AI', date: 'June 12, 2026', readTime: '6 min read', excerpt: 'A practical way to identify where intelligence can make work meaningfully better.', body: ['Most AI programmes do not fail because the technology is weak. They stall when a promising demonstration has no clear owner, operating change, or measure of value.', 'Start with the decisions and workflows where people lose time, context, or confidence. Then design a small, governed intervention that can be evaluated in the real work.', 'Practical adoption treats data quality, human oversight, and change management as part of the product—not work to be solved later.'] },
  { slug: 'modernisation-is-an-operating-decision', title: 'Modernisation is an operating decision', category: 'Cloud', date: 'May 28, 2026', readTime: '5 min read', excerpt: 'Why technology renewal works best when delivery and business priorities stay connected.', body: ['Modernisation is often described as a technical migration. In practice, it is a decision about how an organisation will operate, release change, and manage risk.', 'A useful roadmap links platform work to the capabilities it unlocks for customers and teams. It makes sequencing visible and avoids treating every legacy component as equally urgent.', 'The goal is not a fashionable architecture. It is a more dependable path for the next important change.'] },
  { slug: 'security-belongs-in-the-design', title: 'Security belongs in the design', category: 'Cybersecurity', date: 'May 7, 2026', readTime: '4 min read', excerpt: 'Security-minded delivery begins before a product reaches production.', body: ['Security is strongest when it is built into decisions about identity, data, integrations, and operational ownership from the earliest stages of delivery.', 'Teams move faster when secure defaults, clear review points, and observable systems are part of their everyday workflow—not a late-stage gate.', 'That approach makes risk easier to discuss and reduces the cost of improving a service over time.'] },
  { slug: 'data-products-for-decisions', title: 'Data products should help decisions travel', category: 'Data & analytics', date: 'April 21, 2026', readTime: '7 min read', excerpt: 'Designing data products that give teams shared context rather than another dashboard.', body: ['The value of a data product is not the volume of information it presents. It is the quality of the shared decision it enables.', 'Useful products connect trusted definitions, appropriate context, and a clear next action. They make uncertainty visible instead of hiding it in a score.', 'That is how analytics becomes part of the operating rhythm, rather than a report that arrives after the moment has passed.'] },
  { slug: 'modernising-without-losing-momentum', title: 'Modernising without losing delivery momentum', category: 'Digital transformation', date: 'April 3, 2026', readTime: '5 min read', excerpt: 'A practical sequence for improving a platform while keeping customer commitments moving.', body: ['A modernisation programme needs room for foundational work and visible progress. The two are not in conflict when the work is sequenced with care.', 'Start by making the constraints explicit, then choose thin slices that improve reliability and create learning for the next release.', 'Sustained momentum comes from making the path understandable to the people who must deliver it.'] },
  { slug: 'enterprise-change-needs-a-product-mindset', title: 'Enterprise change needs a product mindset', category: 'Enterprise modernisation', date: 'March 16, 2026', readTime: '6 min read', excerpt: 'Why durable internal services deserve the same care as customer-facing products.', body: ['Internal systems shape customer outcomes through the people who rely on them every day.', 'A product mindset brings clear ownership, feedback loops, and a commitment to improve the experience over time.', 'It helps organisations avoid the false choice between transformation programmes and practical service improvement.'] },
] as const;
