import { db, closeDbPool } from '@/lib/db'; import { runBacktestQueuePreflight } from './backtestQueuePreflight'; import { MysqlBacktestOwnershipAuthority } from '@/lib/backtesting/queue/ownershipAuthority'; import { decideProcessorAuthority } from '@/lib/backtesting/queue/processorAuthority'; import type { BacktestProcessorOwner } from '@/lib/backtesting/queue/ownership'; import { execFileSync } from 'node:child_process';import fs from'node:fs/promises';import{validateDeterministicBacktestFixture}from'@/lib/backtesting/parity/fixtureValidation';
const owner=(value:string|undefined,fallback:BacktestProcessorOwner):BacktestProcessorOwner=>['monolith','service','disabled'].includes(value??'')?value as BacktestProcessorOwner:fallback; const epoch=(value:string|undefined)=>value==null?undefined:Number(value);
async function main(){const checks:Record<string,unknown>={};let ok=true;let authority;
  try{authority=await new MysqlBacktestOwnershipAuthority().read();checks.authority=authority;}catch(error){checks.authorityError=String(error);ok=false;}
  const monolith=decideProcessorAuthority({processorType:'monolith',configuredOwner:owner(process.env.MONOLITH_BACKTEST_PROCESSOR_OWNER??process.env.BACKTEST_PROCESSOR_OWNER,'monolith'),configuredEpoch:epoch(process.env.MONOLITH_BACKTEST_OWNERSHIP_EPOCH??process.env.BACKTEST_OWNERSHIP_EPOCH),authority,authorityError:authority?undefined:checks.authorityError,applicationVersion:process.env.APP_VERSION??'unknown'});
  const worker=decideProcessorAuthority({processorType:'service',configuredOwner:owner(process.env.WORKER_BACKTEST_PROCESSOR_OWNER,'disabled'),configuredEpoch:epoch(process.env.WORKER_BACKTEST_OWNERSHIP_EPOCH),workerEnabled:process.env.WORKER_BACKTEST_WORKER_ENABLED==='true',authority,authorityError:authority?undefined:checks.authorityError,applicationVersion:process.env.APP_VERSION??'unknown',workerVersion:process.env.BACKTEST_WORKER_VERSION??'unknown'});checks.monolith=monolith;checks.worker=worker;
  try{checks.queuePreflight=await runBacktestQueuePreflight();const migrations:any=await db.query(`SELECT version,checksum,applied_at FROM backtest_schema_migrations WHERE version IN ('016','017') ORDER BY version`);checks.migrations=migrations.rows;if(migrations.rows.length!==2)ok=false;const active:any=await db.query(`SELECT ownership_epoch,processor_type,status,COUNT(*) count,COUNT(DISTINCT processor_id) processors,MIN(lease_expires_at) earliest_lease,MAX(lease_expires_at) latest_lease FROM backtest_runs WHERE status IN ('running','cancel_requested') GROUP BY ownership_epoch,processor_type,status`);checks.activeJobs=active.rows;checks.obsoleteActiveJobs=authority?active.rows.filter((r:any)=>Number(r.ownership_epoch)!==authority.epoch):active.rows;const conflicts:any=await db.query(`SELECT ownership_epoch,COUNT(DISTINCT processor_type) processor_types FROM backtest_runs WHERE status IN ('running','cancel_requested') GROUP BY ownership_epoch HAVING COUNT(DISTINCT processor_type)>1`);checks.conflictingProcessors=conflicts.rows;if((checks.obsoleteActiveJobs as any[]).length||conflicts.rows.length)ok=false;}catch(error){checks.databaseError=String(error);ok=false;}
  checks.settings={leaseMs:Number(process.env.BACKTEST_WORKER_LEASE_DURATION_MS??60000),heartbeatMs:Number(process.env.BACKTEST_WORKER_HEARTBEAT_INTERVAL_MS??15000),workerConcurrency:Number(process.env.BACKTEST_WORKER_MAX_CONCURRENCY??1)};if((checks.settings as any).workerConcurrency!==1||(checks.settings as any).leaseMs<(checks.settings as any).heartbeatMs*3)ok=false;
  checks.operator=process.env.BACKTEST_OPERATOR_ID??null;if(!checks.operator)ok=false;checks.commit=process.env.GIT_COMMIT??(()=>{try{return execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim()}catch{return'unknown'}})();checks.persistedParity='not-executed';
  try{const fixture=await validateDeterministicBacktestFixture();checks.fixture=fixture;if(!fixture.ok)ok=false;}catch(error){checks.fixtureError=String(error);ok=false;}
  try{const parity=JSON.parse(await fs.readFile('artifacts/backtest-parity-report.json','utf8'));checks.persistedParity=parity;if(parity.verdict!=='passed')ok=false;}catch(error){checks.parityReportError=String(error);ok=false;}
  for(const [name,file] of [['twoProcess','artifacts/backtest-two-process-report.json'],['rollback','artifacts/backtest-rollback-report.json']] as const){try{const evidence=JSON.parse(await fs.readFile(file,'utf8'));checks[name]=evidence;if(evidence.verdict!=='passed'&&evidence.ok!==true)ok=false;}catch(error){checks[`${name}Error`]=String(error);ok=false;}}
  try{const authorization=JSON.parse(await fs.readFile('artifacts/backtest-authorization-report.json','utf8'));checks.authorizationRegression=authorization;if(authorization.ok!==true)ok=false;}catch(error){checks.authorizationRegressionError=String(error);ok=false;}
  try{await fs.access('scripts/backtestWorkerRollback.ts');checks.rollbackTool=true;}catch{checks.rollbackTool=false;ok=false;}checks.auditOutput=process.env.BACKTEST_AUDIT_OUTPUT??null;if(!checks.auditOutput)ok=false;
  if(process.env.BACKTEST_WORKER_INTERNAL_URL){try{const ready=await fetch(`${process.env.BACKTEST_WORKER_INTERNAL_URL}/ready`);const metrics=await fetch(`${process.env.BACKTEST_WORKER_INTERNAL_URL}/metrics`);checks.workerEndpoint={readinessStatus:ready.status,readiness:await ready.json(),metricsStatus:metrics.status};if(!metrics.ok)ok=false;}catch(error){checks.workerEndpointError=String(error);ok=false;}}else{checks.workerEndpointError='BACKTEST_WORKER_INTERNAL_URL is required';ok=false;}
  if(authority?.owner==='monolith'&&!monolith.allowed)ok=false;if(authority?.owner==='service'&&!worker.allowed)ok=false;if(authority?.owner==='disabled'&&(monolith.allowed||worker.allowed))ok=false;
  const report={ok,timestamp:new Date().toISOString(),checks};await fs.writeFile('artifacts/backtest-staging-preflight-report.json',JSON.stringify(report,null,2));await closeDbPool();console.error(`Backtest staging preflight: ${ok?'PASS':'BLOCKED'} owner=${authority?.owner??'unavailable'} epoch=${authority?.epoch??'unavailable'}`);console.log(JSON.stringify(report,null,2));if(!ok)process.exitCode=2;
} void main().catch(error=>{console.error(JSON.stringify({ok:false,error:String(error)}));process.exitCode=1});
