import Link from 'next/link';
import { INSIGHTS } from '@/lib/data';
import styles from '@/styles/InsightDetail.module.scss';

const ALL_ARTICLES = [
  ...INSIGHTS,
  {
    category: 'Platform Thinking',
    title:    'What modular architecture actually means for a trading intelligence platform',
    excerpt:  'Modularity is not simply a technical property. In a multi-engine intelligence platform, it determines how capabilities compose, how quality gates interact, and how the system behaves when one module has better data than another.',
    readTime: '7 min read',
    date:     'November 2024',
    slug:     'modular-architecture',
    body: `
Modularity is one of those terms that gets applied so broadly it risks losing meaning. In software, it is often used simply to mean "things are separated into files." In platform design, it should mean something far more specific: discrete, independently deployable capabilities with clearly defined interfaces between them.

For a trading intelligence platform, the distinction matters in ways that become immediately practical.

**What modular architecture enables**

When a platform is built as a collection of modules with clean interfaces, several things become possible that would not be possible in a monolithic architecture.

First, each module can be developed to full production quality before the next begins. There are no dependencies that require two half-built systems to coordinate before either can be tested or deployed. The Intelligence Engine in Quantorus365 functions completely independently of the Risk Engine still under development.

Second, modules can be aware of one another without being coupled to one another. The scenario engine reads the market stance engine's output. The rejection engine reads the portfolio fit engine's output. But each can be updated, replaced, or expanded without requiring the others to change.

Third, quality gates can be structural. The eleven-gate rejection engine in the Intelligence Engine exists because each gate is a composable, independently evaluable check. This would not be architecturally possible in a system where risk logic, portfolio logic, and signal logic were all intertwined.

**What modularity is not**

Modularity is not the same as having separate files. It is not the same as breaking a monolith into microservices. It is not the same as building a plugin architecture.

True modularity, in the context of an intelligence platform, means that each module has a single, clear domain of responsibility. The macro intelligence engine is responsible for one thing: providing a reliable, structured view of the macro environment. It does not also do options pricing. It does not also do signal generation. Its interface with other modules is precisely defined.

**The compound benefit**

As each module matures, the compound benefit of modularity becomes apparent. A signal that is generated by the Intelligence Engine can be evaluated against portfolio context from the portfolio fit engine, calibrated against the macro regime from the macro engine, and further filtered by derivatives positioning from the options engine — each as an independent check, each contributing a specific dimension of intelligence that the others cannot provide.

This is what a genuinely institutional decision architecture looks like. Not a dashboard with many widgets. A structured intelligence stack where every layer has a defined purpose and a defined relationship to the layers around it.
    `,
  },
  {
    category: 'Risk Systems',
    title:    'Building risk as a gatekeeper: the eleven-gate architecture',
    excerpt:  'Risk as a display metric and risk as a gatekeeper are architecturally different things. One is computed after a signal is formed. The other determines whether a signal is permitted to form at all.',
    readTime: '10 min read',
    date:     'October 2024',
    slug:     'risk-as-gatekeeper',
    body: `
There is a design decision at the heart of every trading intelligence system that most platforms make without acknowledging it: where in the processing chain does risk sit?

In the vast majority of retail and prosumer tools, risk is computed after a signal is generated. The system identifies an opportunity, prices the setup, calculates an entry and stop, and then appends a risk label — typically a score from 1 to 5, or a colour-coded indicator — to the output.

The problem with this approach is architectural, not cosmetic. Risk that is computed after a signal is formed is a display metric. It informs the user, but it does not constrain the system.

**Risk as a gatekeeper**

The alternative is to embed risk as a structural constraint in the signal generation process itself. In this architecture, risk does not describe a signal — it determines whether a signal is permitted to exist.

This is the principle behind the eleven-gate rejection engine in Quantorus365. Eleven independent quality checks must pass before a signal is emitted. If any single gate fails, no signal reaches the user. The gates are evaluated in a defined sequence: data quality first, then strategy fit, then scenario alignment, then regime, then risk-reward, then confidence, then risk score, then liquidity, then stop distance sanity, then portfolio fit.

**Why the order of gates matters**

Gates are not evaluated simultaneously. The sequence is designed to fail fast on the cheapest checks first. Data quality — is this market data fresh and reliable? — is checked before anything else, because there is no point computing a sophisticated confidence model on stale or low-quality input.

The most computationally expensive checks — portfolio fit, which requires reading live position data and computing sector exposure — run last, because they should only run if everything upstream has already passed.

**What changes when risk is a gatekeeper**

When risk is a display metric, a system can — and does — produce many signals. When risk is a gatekeeper, the signal output is dramatically smaller, but every signal that does emerge has cleared a structured set of institutional-grade checks.

This is not a comfortable architectural choice for a product that wants to maximise engagement metrics. Users who see fewer signals may initially interpret this as lower quality. The opposite is true. The signal that clears eleven gates is structurally more sound than the signal that cleared none.

The discipline of rejection is, ultimately, the only honest value proposition an intelligence platform can offer.
    `,
  },
];

export function generateStaticParams() {
  return ALL_ARTICLES.map(a => ({ slug: a.slug }));
}

export default function InsightArticle({ params }: { params: { slug: string } }) {
  const article = ALL_ARTICLES.find(a => a.slug === params.slug);

  if (!article) {
    return (
      <div className={styles.notFound}>
        <p>Article not found.</p>
        <Link href="/insights">← Back to Insights</Link>
      </div>
    );
  }

  const otherArticles = ALL_ARTICLES.filter(a => a.slug !== params.slug).slice(0, 3);

  return (
    <>
      <section className={styles.heroSection}>
        <div className={`container ${styles.heroContainer}`}>
          <Link href="/insights" className={styles.backLink}>
            ← Insights
          </Link>

          <div className={styles.metaRow}>
            <span className={styles.metaCategory}>
              {article.category}
            </span>
            <span className={styles.metaSeparator}>·</span>
            <span className={styles.metaText}>
              {article.date}
            </span>
            <span className={styles.metaSeparator}>·</span>
            <span className={styles.metaText}>
              {article.readTime}
            </span>
          </div>

          <h1 className={styles.articleTitle}>{article.title}</h1>
          <p className={styles.articleExcerpt}>
            {article.excerpt}
          </p>
        </div>
      </section>

      <section className={styles.bodySection}>
        <div className={`container ${styles.bodyContainer}`}>
          {'body' in article && article.body ? (
            <div className={styles.bodyInner}>
              {(article as any).body.trim().split('\n\n').map((para: string, i: number) => {
                if (para.startsWith('**') && para.endsWith('**')) {
                  return (
                    <h3 key={i} className={styles.bodyHeading}>
                      {para.replace(/\*\*/g, '')}
                    </h3>
                  );
                }
                return (
                  <p key={i} className={styles.bodyPara}>
                    {para.replace(/\*\*(.*?)\*\*/g, '$1')}
                  </p>
                );
              })}
            </div>
          ) : (
            <p className={styles.bodyMissing}>
              Full article content available on request. This insight is part of Quantorus365&apos;s platform thinking series.
            </p>
          )}

          <div className={styles.disclaimer}>
            <p className={styles.disclaimerText}>
              This insight reflects the product philosophy and architectural thinking behind Quantorus365. It does not constitute financial advice or investment guidance. Quantorus365 is a platform in active development.
            </p>
          </div>
        </div>
      </section>

      {otherArticles.length > 0 && (
        <section className={styles.relatedSection}>
          <div className="container">
            <p className={styles.relatedLabel}>
              Further reading
            </p>
            <div className={styles.relatedGrid}>
              {otherArticles.map(a => (
                <Link key={a.slug} href={`/insights/${a.slug}`} className={styles.relatedCard}>
                  <span className={styles.relatedCategory}>
                    {a.category}
                  </span>
                  <h4 className={styles.relatedTitle}>
                    {a.title}
                  </h4>
                  <span className={styles.relatedMeta}>
                    {a.readTime}
                  </span>
                </Link>
              ))}
            </div>
          </div>
        </section>
      )}
    </>
  );
}
